class PolyGroup:
    def __init__(self) -> None: ...
    def addPolyData(self, data: list[int]) -> None: ...
    def getPolyCount(self) -> int: ...
    def getPoly(self, n: int) -> list[int]: ...
    def area(self) -> float: ...
    def clear(self) -> None: ...
    def empty(self) -> bool: ...
    def assign(self) -> None: ...
    def difference(self, pg2: PolyGroup) -> None: ...
    def intersection(self, pg2: PolyGroup) -> None: ...
    def merge(self, pg2: PolyGroup) -> None: ...
    def exor(self, pg2: PolyGroup) -> None: ...
    def trapezoids(self) -> None: ...
    def resize(
        self,
        value: float,
        corner_fill_arc: bool,
        num_circle_segments: int,
    ) -> None: ...
